version: "3.9"

services:
  postgres:
    image: postgres:16 # загржаемй образ имя:тег
    container_name: postgres # имя контейнера
    restart: unless-stopped  # автоперезапуск
    environment: # настройка переменных окружения
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports: # проброс портов (порт на хосте):(порт в контейнере)
      - "5432:5432"
    volumes: # хранилище
      - pg_data:/var/lib/postgresql/data
    networks: # к каой сети подключаемся
      - pg-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pg-net

  simply-server:
    image: simply:0.0.1
    container_name: simply-server
    restart: unless-stopped           
    ports:
      - "8090:8090"                  # проброс порта для сервера
    depends_on:
      - postgres
    networks:
      - pg-net

volumes: # ввиду отсутсвия ручных настроек docker сам выделяет хранилище для данных postgress
  pg_data:

networks: 
  pg-net: # создаем docker мост для сети контейнеров
    driver: bridge
